theme: minima

author: Pratap Reddy
email: "pratapreddy@rogers.com"

title: Pratap Reddy

nav:
  - title: Pratap Reddy
    url: /
  - title: Books
    url: /books/
  - title: Education
    url: /education/
