theme: minima

author:
  name: Pratap Reddy
  email: pratapreddy@rogers.com

nav:
  - title: Pratap Reddy
    url: /
  - title: Books
    url: /books/
  - title: Education
    url: /education/
