theme: minima

title: Pratap Reddy

nav:
  - title: Pratap Reddy
    url: /
  - title: Books
    url: /books/
  - title: Education
    url: /education/
  - title: Awards
    url: /awards/

minima:
  hide_site_feed_link: true
  social_links:
    - title: Instagram
      url: "https://instagram.com/pratapreddycanada"
      icon: instagram
    - title: LinkedIn
      url: "https://linkedin.com/in/pratap-reddy-02535a15a"
      icon: linkedin
    - title: Email
      url: "mailto:pratapreddy@rogers.com"
      icon: envelope