theme: minima

author: Pratap Reddy
email: "pratapreddy@rogers.com"

title: Pratap Reddy

nav:
  - title: Pratap Reddy
    url: /
  - title: Books
    url: /books/
  - title: Education
    url: /education/

minima:
  hide_site_feed_link: true
  social_links:
    - title: Instagram
      url: "instagram.com/pratapreddycanada"
      icon: /assets/images/instagram-53-32.png